export const NETWORK_DEMAND_SOLANA_DEVNET =
  "FsuAo548DuET7eMeGtyKjnJo8tZaJbR2rMq4u7q8dU8a";
export const STAKING_DATABASE_SOLANA_DEVNET =
  "56pXzxf9ZZ4QwHitWy65s8D2brfczWTDp3DcKQjVHNL1";
export const STAKE_POOL_SOLANA_DEVNET =
  "EopS2mu3u3QTxVFzEtguYp64ZFD6KEPZjVfcrAsp2nGh";
export const DISTRIBUTION_POOL_SOLANA_DEVNET =
  "DeEZA5PkL1eebgKYEyVhMhaxA3tCaLybDkF9BgZvs1yU";
export const STAKING_MANAGER_SOLANA_DEVNET =
  "FyLUJGfEcnJF2HQLCJonQQtHxPK2EjHmxFRL84XMS6qk";
export const REBASE_ENGINE_SOLANA_DEVNET =
  "FSNcCfSmUYrZDeiwvZvLyaSQSx16YjWtMWaF5bCofk8h";

export const STAKING_PROGRAM_ID =
  "5vKewTXsasvYC9ab7gqmogeDrE8j88b9yVg1afz3T36L";
