export { default as Logo } from './logo.png'
export { default as LogoSvg } from './logo.svg'
export { default as Menu } from './menu.svg'
export { default as HeroBanner } from './heroBanner.svg'
export { default as HeroBannerBlack } from './hero-banner-black.svg'

export { default as Robot } from './robot.png'
export { default as SolanaIcon } from './solanaIcon.svg'
export { default as HeroBannerMobile } from './heroBannerMobile.png'
export { default as DottedWaves } from './dottedWaves.png'
export { default as DottedWavesGreen } from './dottedWavesGreen.png'
export { default as RingOne } from './ringOne.png'
export { default as RingTwo } from './ringTwo.png'
export { default as Telegram } from './telegram.svg'
export { default as Discord } from './discord.svg'
export { default as Twitter } from './twitter.png'
export { default as Abstract } from './abstract.svg'
export { default as ColoredSolana } from './coloredSolana.svg'
export { default as AbstractMobile } from './abstractMobile.svg'
export { default as RingThree } from './ringThree.png'
export { default as RingFour } from './ringFour.png'
export { default as AssistanceBanner } from './assistanceBanner.svg'
export { default as DottedWavesGreenMobile } from './dottedWavesGreenMobile.png'
export { default as MobileLogo } from './mobileLogo.png'
export { default as GreenSpinner } from './greenSpinner.svg'
export { default as BlueSpinner } from './blueSpinner.svg'
export { default as YellowSpinner } from './yellowSpinner.svg'

export { default as CheersLand } from './cheersLand.png'
export { default as KleinLabs } from './kleinLabs.png'
export { default as TrustFi } from './trustFi.png'
export { default as CryptoPlayers } from './cryptoPlayers.png'

export { default as GreenBar } from './greenBar.svg'
export { default as BlueBar } from './blueBar.svg'

export { default as RedNodeAnimation } from './images/Red Node.mp4'
export { default as GoldNodeAnimation } from './images/Gold Node.mp4'
export { default as GreenNodeAnimation } from './images/Green Node.mp4'
export { default as BlueNodeAnimation } from './images/Blue Node.mp4'
export { default as IridescenceNodeAnimation } from './images/Iridescence Node.mp4'

export { default as HeroBackground } from './images/hero_bg.svg'
export { default as TarsLogoTextWhite } from './images/tars_logo_text_white.svg'
export { default as ForwardIcon } from './images/forward_icon.svg'
export { default as PopUpBackground } from './PopUpBackground.svg'
